#!/bin/sh
# A Tcl comment, whose contents don't matter \
if command -v vivado; then CMD=vivado ; else CMD=vivado_lab ;fi && exec $CMD -mode batch -source "$0" -tclargs usr_$USER "$@"

# index of the board, if there are more than one
set index {0}
set u "erase"

set_param xicom.use_bitstream_version_check false
open_hw
catch {disconnect_hw_server}
connect_hw_server
current_hw_target [get_hw_targets */xilinx_tcf/Digilent/*]
set_property PARAM.FREQUENCY 15000000 [get_hw_targets */xilinx_tcf/Digilent/*]
open_hw_target
current_hw_device [lindex [get_hw_devices xcvu9p_0] $index]
refresh_hw_device -update_hw_probes false [current_hw_device]
create_hw_cfgmem -hw_device [current_hw_device] -mem_dev [lindex [get_cfgmem_parts {mt25qu01g-spi-x1_x2_x4_x8}] 0]

#			 PROGRAM.ADDRESS_RANGE {use_file} \

set_property -dict [ list \
			 PROGRAM.ADDRESS_RANGE {entire_device} \
			 PROGRAM.UNUSED_PIN_TERMINATION {pull-none} \
			 PROGRAM.PRM_FILE {} \
			 PROGRAM.FILES "" \
			 PROGRAM.BLANK_CHECK 0 \
			 PROGRAM.ERASE 1 \
			 PROGRAM.CFG_PROGRAM 0 \
			 PROGRAM.VERIFY 0 \
			 PROGRAM.CHECKSUM 0 \
			] [current_hw_cfgmem]

if {![string equal [get_property PROGRAM.HW_CFGMEM_TYPE [current_hw_device]] [get_property MEM_TYPE [get_property CFGMEM_PART [current_hw_cfgmem]]] ]} {
    create_hw_bitstream -hw_device [current_hw_device] [get_property PROGRAM.HW_CFGMEM_BITFILE [current_hw_device]]
    program_hw_devices
}

program_hw_cfgmem -hw_cfgmem [current_hw_cfgmem]

close_hw_target
disconnect_hw_server
close_hw
