//
// Generated by Bluespec Compiler, version 2017.07.A (build 4f44cbe, 2017-07-21)
//
// On Sat Jun  2 16:42:51 EDT 2018
//
//
// Ports:
// Name                         I/O  size props
// not_used                       O     1 const
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkSceMiUInt32Parameter(not_used);
  parameter [31 : 0] n = 32'b0;

  // value method not_used
  output not_used;

  // signals for module outputs
  wire not_used;

  // value method not_used
  assign not_used = 1'd0 ;
endmodule  // mkSceMiUInt32Parameter

