/*
 * Generated by Bluespec Compiler, version 2017.07.A (build e1df8052c, 2017-07-21)
 * 
 * 
 * 
 */
#ifndef __vpi_wrapper_c_debug_client_disconnect_h__
#define __vpi_wrapper_c_debug_client_disconnect_h__

#include <vpi_user.h>

/* registration function */
void c_debug_client_disconnect_vpi_register();

/* VPI wrapper function */
PLI_INT32 c_debug_client_disconnect_calltf(PLI_BYTE8 *user_data);

#endif /* ifndef __vpi_wrapper_c_debug_client_disconnect_h__ */
