//
// Generated by Bluespec Compiler, version 2017.07.A (build e1df8052c, 2017-07-21)
//
// On Wed Feb 27 10:29:54 EST 2019
//
//
// Ports:
// Name                         I/O  size props
// o                              O     1
// odiv2                          O     1
// i_i                            I     1
// ib_ib                          I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module ibufds_gte4(o,
		   odiv2,
		   i_i,
		   ib_ib);
  // value method o
  output o;

  // value method odiv2
  output odiv2;

  // action method i
  input  i_i;

  // action method ib
  input  ib_ib;

  // signals for module outputs
  wire o, odiv2;

  // ports of submodule _unnamed_
  wire _unnamed_$I, _unnamed_$IB, _unnamed_$O, _unnamed_$ODIV2;

  // value method o
  assign o = _unnamed_$O ;

  // value method odiv2
  assign odiv2 = _unnamed_$ODIV2 ;

  // submodule _unnamed_
  IBUFDS_GTE4 _unnamed_(.I(_unnamed_$I),
			.IB(_unnamed_$IB),
			.O(_unnamed_$O),
			.ODIV2(_unnamed_$ODIV2));

  // submodule _unnamed_
  assign _unnamed_$I = i_i ;
  assign _unnamed_$IB = ib_ib ;
endmodule  // ibufds_gte4
